use sha2::{Digest, Sha256};
use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
};
fn hash(raw: &[u8]) -> String {
    format!("{:x}", Sha256::digest(raw))
}
fn walk(root: &Path, dir: &Path, out: &mut BTreeMap<String, String>) {
    for item in fs::read_dir(dir).expect("reasoning sources") {
        let path = item.unwrap().path();
        let name = path.file_name().unwrap().to_str().unwrap();
        if name.starts_with('.') {
            continue;
        }
        if path.is_dir() {
            walk(root, &path, out);
        } else if path.extension().is_some_and(|s| s == "lean")
            && !["Proof", "Audit"]
                .iter()
                .any(|prefix| name.starts_with(prefix))
        {
            println!("cargo:rerun-if-changed={}", path.display());
            out.insert(
                path.strip_prefix(root)
                    .unwrap()
                    .to_str()
                    .unwrap()
                    .replace('\\', "/"),
                hash(&fs::read(path).unwrap()),
            );
        }
    }
}
fn files(dir: &Path, out: &mut Vec<PathBuf>) {
    for item in fs::read_dir(dir).expect("shared files") {
        let path = item.unwrap().path();
        if path.is_dir() {
            files(&path, out);
        } else {
            out.push(path);
        }
    }
}
/// A published crate carries nothing from outside its directory, so everything this crate
/// embeds or fingerprints lives under shared/, with the licence beside this manifest. Two of
/// those files are also read from outside the crate: the Lean sources, which the reasoning
/// runtime is built from and the ordinary program is packaged from. In a checkout of the
/// repository a copy that differs from its original stops the build rather than shipping
/// bytes that describe something else.
fn check_copies(sources: &BTreeMap<String, String>) {
    let (Ok(here), Ok(parent)) = (
        Path::new(".").canonicalize(),
        Path::new("..").canonicalize(),
    ) else {
        return;
    };
    let originals = Path::new("../scripts");
    if here != parent.join("native") || !originals.join("session/lean/Main.lean").is_file() {
        return;
    }
    let mut copies = Vec::new();
    files(Path::new("shared/session/lean"), &mut copies);
    let mut pairs = vec![(PathBuf::from("LICENSE"), PathBuf::from("../LICENSE"))];
    pairs.push((PathBuf::from("shared/board.png"), PathBuf::from("../assets/diagrams/two-working-modes.png")));
    for copy in copies {
        let outside = originals.join(copy.strip_prefix("shared").unwrap());
        pairs.push((copy, outside));
    }
    let mut stale = Vec::new();
    for (copy, outside) in pairs {
        println!("cargo:rerun-if-changed={}", outside.display());
        if fs::read(&copy).ok() != fs::read(&outside).ok() {
            stale.push(copy.display().to_string());
        }
    }
    let root = originals.join("reasoning/lean");
    println!("cargo:rerun-if-changed={}", root.display());
    let mut current = BTreeMap::new();
    walk(&root, &root, &mut current);
    if &current != sources {
        stale.push("shared/reasoning/lean".into());
    }
    assert!(
        stale.is_empty(),
        "these differ from the file they are kept in step with: {}\n\
         the licence comes from the repository root, and the Lean sources under scripts/ are \
         the same sources the runtime build and the Lean package read",
        stale.join(", ")
    );
}
/// A crate packaged for crates.io carries the manifest Cargo normalized for the registry,
/// with the original beside it as Cargo.toml.orig. Hashing the original gives a build from
/// crates.io the adapter identity of the same version built from the repository.
fn manifest() -> Vec<u8> {
    let manifest = fs::read("Cargo.toml").unwrap();
    if manifest.starts_with(b"# THIS FILE IS AUTOMATICALLY GENERATED BY CARGO")
        && let Ok(original) = fs::read("Cargo.toml.orig")
    {
        println!("cargo:rerun-if-changed=Cargo.toml.orig");
        return original;
    }
    manifest
}
fn main() {
    println!("cargo:rerun-if-changed=shared");
    println!("cargo:rerun-if-changed=LICENSE");
    for schema in [
        "shared/assessment.schema.json",
        "shared/reasoning/assessment.schema.json",
        "shared/reasoning/history_assessment.schema.json",
    ] {
        println!("cargo:rerun-if-changed={schema}");
    }
    let root = Path::new("shared/reasoning/lean");
    println!("cargo:rerun-if-changed={}", root.display());
    let mut sources = BTreeMap::new();
    walk(root, root, &mut sources);
    assert!(!sources.is_empty());
    check_copies(&sources);
    let ordinary_source = "shared/session/lean/Main.lean";
    println!("cargo:rerun-if-changed={ordinary_source}");
    println!(
        "cargo:rustc-env=KPOP_ORDINARY_SOURCE_SHA256={}",
        hash(&fs::read(ordinary_source).unwrap())
    );
    println!(
        "cargo:rustc-env=KPOP_REASONING_SOURCE_SHA256={}",
        hash(&serde_json::to_vec(&sources).unwrap())
    );
    let mut adapter = BTreeMap::new();
    let mut paths = fs::read_dir("src")
        .unwrap()
        .map(|p| p.unwrap().path())
        .filter(|p| p.extension().is_some_and(|s| s == "rs"))
        .collect::<Vec<_>>();
    paths.extend(["Cargo.lock", "Cargo.toml", "build.rs"].map(Into::into));
    paths.sort();
    for path in paths {
        println!("cargo:rerun-if-changed={}", path.display());
        let bytes = if path == Path::new("Cargo.toml") {
            manifest()
        } else {
            fs::read(&path).unwrap()
        };
        adapter.insert(path.to_str().unwrap().to_owned(), hash(&bytes));
    }
    println!(
        "cargo:rustc-env=KPOP_REASONING_ADAPTER_SHA256={}",
        hash(&serde_json::to_vec(&adapter).unwrap())
    );
}
