"""The page chrome. Record prose is never translated here."""

WORDS = {'en': {'dir': 'ltr',
        'untitled': 'What is known here',
        'tab_now': 'Now',
        'tab_record': 'Record',
        'tab_tree': 'Tree',
        'purpose': 'Everything on this tab was picked for one purpose — ',
        'purpose_sub': 'The {record} tab has all {n} entries and judgments, arranged by nothing.',
        'counts': '{e} entries and {j} judgments',
        'need_person': '. {n} need a person',
        'updated': '. Last updated {d}',
        'judgments': 'Judgments',
        'derived': 'worked out',
        'rest': 'rests on {n} more &mdash; hover the line above',
        'awaited': 'declared missing - this judgment is waiting on it',
        'not_here': 'not an entry in this record',
        'holds': 'holds',
        'says': {'broken': 'rests on something that is not in this record',
                 'falsified': 'its own condition for being wrong now holds',
                 'moved': 'something it rests on no longer matches what it last saw',
                 'unchecked': 'has never been checked against one of the things it rests on',
                 'blocked': 'waiting on something nobody has recorded yet',
                 'no_predicate': 'nothing here would show it to be wrong'},
        'today': 'today',
        'no_shape': 'This arrangement records no shape, so nothing can tell whether it went stale. '
                    'Add a <code>shape:</code> block (printed on stderr when this page was '
                    'generated).',
        'shape_moved': 'The record has changed shape since this arrangement was written &mdash; ',
        'shape_moved_end': '. The sections below still fill themselves, but the sections '
                           'themselves may no longer be the right ones.',
        'fell_back': ' &mdash; fell back to the default shape',
        'section_empty': 'Nothing in the record matches this section. It is about something the '
                         'record no longer holds.',
        'spill': 'Not covered by this arrangement',
        'spill_why': 'Flagged, and no section above picked it up. This section is written by the '
                     'page, not by the brief.',
        'tree_alt': 'the record as a tree',
        'tree_lede': 'The whole record as one growing thing — roots are what was read from the '
                     'world, the canopy is what was concluded from it. Hover anything.',
        'tree_legend': 'roots — read from the world &middot; branches — worked out &middot; '
                       'blossoms — concluded &middot; the trunk is where they meet',
        'tree_more': '... and {n} more roots below the grass',
        'footer': 'Hover any reference for where it came from. Click to pin, click a dependency to '
                  'walk to it, Esc to step back. While a card is open, a solid outline marks '
                  'everything that rests on it and a dashed one what it rests on. Generated from '
                  'the record - nothing here was typed twice.',
        'footer_brief': ' The <b>{now}</b> tab is an arrangement someone chose; <b>{record}</b> is '
                        'everything, arranged by nothing.',
        'concludes': 'concludes',
        'rests_on': 'rests on',
        'wrong_if': 'wrong if',
        'blocked': 'blocked',
        'because': 'because',
        'value': 'value',
        'rule': 'rule',
        'source': 'from',
        'at': 'at',
        'file': 'file',
        'url': 'url',
        'as_of': 'as of',
        'used_by': 'used by',
        'back': '←',
        'tree_btn': 'tree',
        'tree_btn_title': 'prune the tree to what this touches',
        'whole_tree': '⟵ the whole tree',
        'uncounted': 'not counted yet',
        'judgment': 'judgment',
        'unverified': 'unverified',
        'review_missing': 'not reviewed against every reference',
        'reopened_by': 'reopened by',
        'asked': 'asked',
        'occasion': 'This tab is for one occasion &mdash; ',
        'serves': 'It serves: ',
        'decided': 'decided ',
        'as': 'as ',
        'stood': 'stood {n} sessions',
        'word': 'on the word of ',
        'contests': 'A {kind} contests this arrangement &mdash; ',
        'hypothesis': 'hypothesis',
        'question': 'question',
        'hypotheses': '{n} hypotheses wait beside this record',
        'hypothesis_one': '1 hypothesis waits beside this record',
        'contested': ', {n} contested',
        'base_only': '. The page draws the base.',
        'entries': 'entries',
        'judgments_count': 'judgments',
        'flagged': 'flagged',
        'blocked_count': 'blocked',
        'sign_absent': '. Its sign has not appeared: ',
        'spill_count': 'spill {n}',
        'unserved_count': '{n} intents no tab serves',
        'drift': 'drift {n}',
        'since': ' since {d}',
        'since_decided': 'since {name} was decided {n}',
        'spill_loose': 'Flagged, or written for an intent no tab serves, and no section above '
                       'picked it up. This section is written by the page, not by the brief.',
        'written_for': 'Written for {intent}, which no tab serves.',
        'was': 'was {v} when this was reviewed',
        'moved_reviewed': 'Moved since this was reviewed: ',
        'moved_read': 'Moved since this was read: ',
        'days_left': '{n} days left',
        'days_ago': '{n} days ago',
        'countdown_for': 'until {name}',
        'footer_tabs': ' The tabs before <b>{record}</b> are arrangements someone chose; '
                       '<b>{record}</b> is everything, arranged by nothing.',
        'truth': 'Truth: ',
        'elsewhere': 'Elsewhere: ',
        'snapshot': 'A snapshot of the record; live clocks count from its dates.',
        'no_destination': 'no link recorded',
        'yes': 'yes',
        'no': 'no'},
 'he': {'dir': 'rtl',
        'untitled': 'מה ידוע כאן',
        'tab_now': 'עכשיו',
        'tab_record': 'הרשומה',
        'tab_tree': 'העץ',
        'purpose': 'כל מה שבלשונית הזו נבחר למטרה אחת — ',
        'purpose_sub': 'בלשונית {record} יש את כל {n} העובדות והשיפוטים, בלי שום סידור.',
        'counts': '{e} עובדות ו-{j} שיפוטים',
        'need_person': '. {n} מהם צריכים אדם',
        'updated': '. עודכן לאחרונה {d}',
        'judgments': 'שיפוטים',
        'derived': 'נגזר',
        'rest': 'נשען על עוד {n} &mdash; רחפו על השורה שלמעלה',
        'awaited': 'הוצהר כחסר — השיפוט הזה ממתין לו',
        'not_here': 'אינו עובדה ברשומה הזו',
        'holds': 'עומד בעינו',
        'says': {'broken': 'נשען על משהו שאינו ברשומה הזו',
                 'falsified': 'התנאי שהוא עצמו הציב לכך שהוא שגוי מתקיים עכשיו',
                 'moved': 'משהו שהוא נשען עליו כבר לא מה שראה לאחרונה',
                 'unchecked': 'מעולם לא נבדק מול אחד הדברים שהוא נשען עליהם',
                 'blocked': 'ממתין למשהו שאיש עוד לא רשם',
                 'no_predicate': 'שום דבר כאן לא יראה שהוא שגוי'},
        'today': 'היום',
        'no_shape': 'הסידור הזה לא רשם את צורת הרשומה, ולכן שום דבר לא יכול לומר אם הוא התיישן. '
                    'הוסיפו בו מקטע <code>shape:</code> (נדפס ל-stderr כשהדף נוצר).',
        'shape_moved': 'הרשומה שינתה צורה מאז שהסידור הזה נכתב &mdash; ',
        'shape_moved_end': '. המקטעים למטה עדיין ממלאים את עצמם, אבל ייתכן שהמקטעים עצמם כבר אינם '
                           'הנכונים.',
        'fell_back': ' &mdash; חזרה לצורת ברירת המחדל',
        'section_empty': 'שום דבר ברשומה לא מתאים למקטע הזה. הוא עוסק במשהו שהרשומה כבר לא מחזיקה.',
        'spill': 'לא נכלל בסידור הזה',
        'spill_why': 'מסומן, ואף מקטע למעלה לא אסף אותו. את המקטע הזה כותב הדף, לא הסידור.',
        'tree_alt': 'הרשומה כעץ',
        'tree_lede': 'כל הרשומה כדבר אחד שגדל — השורשים הם מה שנקרא מהעולם, והצמרת היא מה שהוסק '
                     'ממנו. רחפו על כל דבר.',
        'tree_legend': 'שורשים — נקרא מהעולם &middot; ענפים — נגזר &middot; פרחים — הוסק &middot; '
                       'הגזע הוא המקום שבו הם נפגשים',
        'tree_more': 'ועוד {n} שורשים מתחת לדשא…',
        'footer': 'רחפו על כל הפניה כדי לראות מאיפה הוא הגיע. לחיצה מקבעת, לחיצה על תלות עוברת '
                  'אליה, Esc חוזר צעד אחורה. כשכרטיס פתוח, קו מלא מסמן כל מה שנשען עליו וקו מקווקו '
                  'את מה שהוא נשען עליו. נוצר מהרשומה — שום דבר כאן לא הוקלד פעמיים.',
        'footer_brief': ' לשונית <b>{now}</b> היא סידור שמישהו בחר; <b>{record}</b> היא הכול, בלי '
                        'שום סידור.',
        'concludes': 'מסקנה',
        'rests_on': 'נשען על',
        'wrong_if': 'שגוי אם',
        'blocked': 'חסום',
        'because': 'כי',
        'value': 'ערך',
        'rule': 'כלל',
        'source': 'מקור',
        'at': 'נלקח ב',
        'file': 'קובץ',
        'url': 'כתובת',
        'as_of': 'נכון ל',
        'used_by': 'משמש את',
        'back': '→',
        'tree_btn': 'עץ',
        'tree_btn_title': 'לגזום את העץ למה שזה נוגע בו',
        'whole_tree': 'כל העץ ⟶',
        'uncounted': 'טרם נספר',
        'judgment': 'שיפוט',
        'unverified': 'לא אומת',
        'review_missing': 'לא נבדק מול כל ההפניות',
        'reopened_by': 'נפתח מחדש בעקבות',
        'asked': 'התבקש',
        'occasion': 'הלשונית נועדה למועד קריאה אחד &mdash; ',
        'serves': 'היא משרתת: ',
        'decided': 'הוחלט ',
        'as': 'בתור ',
        'stood': 'עמד במשך {n} סשנים',
        'word': 'לפי בקשת ',
        'contests': '{kind} חולקת על הסידור הזה &mdash; ',
        'hypothesis': 'השערה',
        'question': 'שאלה',
        'hypotheses': '{n} השערות ממתינות לצד הרשומה',
        'hypothesis_one': 'השערה אחת ממתינה לצד הרשומה',
        'contested': ', {n} במחלוקת',
        'base_only': '. הדף מציג את הבסיס.',
        'entries': 'עובדות',
        'judgments_count': 'שיפוטים',
        'flagged': 'מסומנים',
        'blocked_count': 'חסומים',
        'sign_absent': '. הסימן שלה טרם הופיע: ',
        'spill_count': 'מחוץ לסידור {n}',
        'unserved_count': '{n} כוונות אינן משורתות',
        'drift': 'סחיפה {n}',
        'since': ' מאז {d}',
        'since_decided': 'מאז ההחלטה {name}: {n}',
        'spill_loose': 'מסומן, או נכתב עבור כוונה ששום לשונית אינה משרתת, ולא נאסף למעלה. המקטע '
                       'נכתב על ידי הדף.',
        'written_for': 'נכתב עבור {intent}, ששום לשונית אינה משרתת.',
        'was': 'היה {v} בעת הבדיקה',
        'moved_reviewed': 'השתנה מאז הבדיקה: ',
        'moved_read': 'השתנה מאז הקריאה: ',
        'days_left': 'נותרו {n} ימים',
        'days_ago': 'לפני {n} ימים',
        'countdown_for': 'עד {name}',
        'footer_tabs': ' הלשוניות לפני <b>{record}</b> הן סידורים שנבחרו; <b>{record}</b> מכילה '
                       'הכול ללא סידור.',
        'truth': 'מקור האמת: ',
        'elsewhere': 'במקום אחר: ',
        'snapshot': 'צילום מצב של הרשומה; השעונים החיים סופרים מהמועדים שבה.',
        'no_destination': 'לא נרשם קישור',
        'yes': 'כן',
        'no': 'לא'},
 'ar': {'dir': 'rtl',
        'untitled': 'ما نعرفه هنا',
        'tab_now': 'الآن',
        'tab_record': 'السجل',
        'tab_tree': 'الشجرة',
        'purpose': 'اختير كل ما في علامة التبويب لغرض واحد — ',
        'purpose_sub': 'تضم علامة {record} جميع العناصر والأحكام، وعددها {n}، دون ترتيب.',
        'counts': '{e} عناصر و{j} أحكام',
        'need_person': '. {n} تحتاج إلى شخص',
        'updated': '. آخر تحديث {d}',
        'judgments': 'الأحكام',
        'derived': 'مشتق',
        'rest': 'يستند إلى {n} أخرى &mdash; مرّر المؤشر فوق السطر',
        'awaited': 'معلن كمفقود — هذا الحكم ينتظره',
        'not_here': 'ليس عنصراً في هذا السجل',
        'holds': 'قائم',
        'says': {'broken': 'يستند إلى شيء غير موجود في السجل',
                 'falsified': 'تحقق شرط خطئه',
                 'moved': 'تغير شيء يستند إليه منذ مراجعته',
                 'unchecked': 'لم يراجع مقابل بعض ما يستند إليه',
                 'blocked': 'ينتظر شيئاً لم يسجل بعد',
                 'no_predicate': 'لا يوجد هنا ما يبيّن خطأه'},
        'today': 'اليوم',
        'no_shape': 'لم يسجل هذا الترتيب شكل السجل؛ لا يمكن معرفة إن كان قد تقادم. راجع الترتيب '
                    'لتسجيل شكله.',
        'shape_moved': 'تغير شكل السجل منذ كتابة هذا الترتيب &mdash; ',
        'shape_moved_end': '. لا تزال الأقسام تتجدد، لكن قد يلزم إعادة النظر في اختيارها.',
        'fell_back': ' &mdash; عودة إلى الشكل الافتراضي',
        'section_empty': 'لا يطابق شيء في السجل هذا القسم.',
        'spill': 'خارج هذا الترتيب',
        'spill_why': 'عناصر معلّمة لم يلتقطها أي قسم. هذا القسم ينشئه السجل.',
        'tree_alt': 'السجل كشجرة',
        'tree_lede': 'السجل كشيء ينمو — الجذور ما قرئ من العالم، والتاج ما استنتج منه. مرّر المؤشر '
                     'على أي عنصر.',
        'tree_legend': 'جذور — قرئ من العالم &middot; فروع — مشتقة &middot; أزهار — استنتاجات '
                       '&middot; الجذع يربطها',
        'tree_more': 'و{n} جذور أخرى تحت العشب…',
        'footer': 'مرّر المؤشر على أي مرجع لقراءة مصدره. انقر لتثبيته، وعلى التبعية لاتباعها، وEsc '
                  'للعودة. الخط المتصل لما يعتمد عليه، والمتقطع لما يستند إليه. مولّد من السجل.',
        'footer_brief': ' علامة <b>{now}</b> ترتيب اختاره شخص؛ <b>{record}</b> يعرض كل شيء دون '
                        'ترتيب.',
        'concludes': 'يستنتج',
        'rests_on': 'يستند إلى',
        'wrong_if': 'خطأ إذا',
        'blocked': 'محجوب',
        'because': 'لأن',
        'value': 'القيمة',
        'rule': 'القاعدة',
        'source': 'المصدر',
        'at': 'عند',
        'file': 'الملف',
        'url': 'الرابط',
        'as_of': 'بتاريخ',
        'used_by': 'يستخدمه',
        'back': '→',
        'tree_btn': 'شجرة',
        'tree_btn_title': 'اعرض ما يتصل بهذا في الشجرة',
        'whole_tree': 'الشجرة كاملة ⟶',
        'uncounted': 'لم يحسب بعد',
        'judgment': 'حكم',
        'unverified': 'غير متحقق',
        'review_missing': 'لم يراجع مقابل كل المراجع',
        'reopened_by': 'يعاد فتحه عند',
        'asked': 'المطلوب',
        'occasion': 'هذه العلامة لمناسبة قراءة واحدة &mdash; ',
        'serves': 'تخدم: ',
        'decided': 'تقرر ',
        'as': 'بصفته ',
        'stood': 'صمد {n} جلسات',
        'word': 'بناء على طلب ',
        'contests': '{kind} يعارض هذا الترتيب &mdash; ',
        'hypothesis': 'فرضية',
        'question': 'سؤال',
        'hypotheses': '{n} فرضيات تنتظر بجانب السجل',
        'hypothesis_one': 'فرضية واحدة تنتظر بجانب السجل',
        'contested': ', {n} موضع خلاف',
        'base_only': '. تعرض الصفحة الأساس.',
        'entries': 'عناصر',
        'judgments_count': 'أحكام',
        'flagged': 'معلّم',
        'blocked_count': 'محجوب',
        'sign_absent': '. لم يظهر شرطه: ',
        'spill_count': 'خارج الترتيب {n}',
        'unserved_count': '{n} مقاصد لا تخدمها أي علامة',
        'drift': 'انجراف {n}',
        'since': ' منذ {d}',
        'since_decided': 'منذ قرار {name}: {n}',
        'spill_loose': 'معلّم أو مكتوب لمقصد لا تخدمه علامة، ولم يلتقطه قسم. هذا القسم مولّد.',
        'written_for': 'كتب من أجل {intent} الذي لا تخدمه أي علامة.',
        'was': 'كان {v} عند المراجعة',
        'moved_reviewed': 'تغير منذ المراجعة: ',
        'moved_read': 'تغير منذ القراءة: ',
        'days_left': 'بقي {n} أيام',
        'days_ago': 'منذ {n} أيام',
        'countdown_for': 'حتى {name}',
        'footer_tabs': ' العلامات قبل <b>{record}</b> ترتيبات اختارها شخص؛ <b>{record}</b> كل شيء '
                       'دون ترتيب.',
        'truth': 'مصدر الحقيقة: ',
        'elsewhere': 'في مكان آخر: ',
        'snapshot': 'لقطة من السجل؛ الساعات الحية تحسب من تواريخه.',
        'no_destination': 'لم يسجل رابط',
        'yes': 'نعم',
        'no': 'لا'}}
