name = "kpopperReasoning"
version = "1.0.0"
defaultTargets = ["kpopper-reasoning"]

[[lean_lib]]
name = "Kernel"

[[lean_lib]]
name = "Protocol"

[[lean_lib]]
name = "CompositionTypes"

[[lean_lib]]
name = "Composition"

[[lean_lib]]
name = "CompositionProtocol"

[[lean_lib]]
name = "Kpopper"

[[lean_lib]]
name = "Proof"

[[lean_exe]]
name = "kpopper-reasoning"
root = "Main"
